# ETL simples com SQLAlchemy Core + Pandas
## Simulando Bronze → Silver → Gold

Neste notebook vamos construir um ETL didático usando **SQLAlchemy Core**, **Pandas** e **PostgreSQL**.

### Fluxo

```text
PostgreSQL
    │
    │ SQL
    ▼
  BRONZE
    │
    │ Pandas
    │ limpeza + cálculos
    ▼
  SILVER
    │
    │ SQL 
    │ agregações
    ▼
   GOLD
    │
    ▼
 Power BI / BI
```

> Objetivo: entender ETL e camadas de dados.

## 1. Instalação

Se necessário:

```bash
pip install pandas sqlalchemy psycopg2-binary
```

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

print("Bibliotecas carregadas!")

Bibliotecas carregadas!

## 2. Conexão com PostgreSQL

Estamos usando **SQLAlchemy Core**, sem ORM.

In [2]:
# Ajuste os dados conforme seu ambiente

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/loja_brasil"
)

print("Engine criada!")

Engine criada!

## 3. Criar o schema do ETL

Vamos utilizar o schema `etl` para armazenar as camadas.

In [3]:
with engine.begin() as conn:
    conn.execute(text("CREATE SCHEMA IF NOT EXISTS etl"))

print("Schema etl criado!")

Schema etl criado!

# 🥉 BRONZE

A Bronze representa os dados **brutos**, próximos da origem.

Vamos extrair dados de `vendas.pedidos` e `vendas.itens_pedido` usando **SQL**.

## 4. EXTRACT — SQL

```sql
SELECT
    p.id_pedido,
    p.data_pedido,
    p.id_cliente,
    i.id_produto,
    i.quantidade,
    i.preco_unitario,
    i.desconto
FROM vendas.pedidos p
INNER JOIN vendas.itens_pedido i
    ON p.id_pedido = i.id_pedido;
```

In [4]:
sql_bronze = text(
    '''
    SELECT
        p.id_pedido,
        p.data_pedido,
        p.id_cliente,
        i.id_produto,
        i.quantidade,
        i.preco_unitario,
        i.desconto
    FROM vendas.pedidos p
    INNER JOIN vendas.itens_pedido i
        ON p.id_pedido = i.id_pedido;
    '''
)

print(sql_bronze)

    SELECT
        p.id_pedido,
        p.data_pedido,
        p.id_cliente,
        i.id_produto,
        i.quantidade,
        i.preco_unitario,
        i.desconto
    FROM vendas.pedidos p
    INNER JOIN vendas.itens_pedido i
        ON p.id_pedido = i.id_pedido;

## 5. Executar o SQL e carregar no Pandas

`pd.read_sql()` recebe o comando SQL e uma conexão SQLAlchemy.

In [5]:
with engine.connect() as conn:
    df_bronze = pd.read_sql(sql_bronze, conn)

df_bronze.head()

,id_pedido,data_pedido,id_cliente,id_produto,quantidade,preco_unitario,desconto
0,1,2025-02-10,8,6,2,159.9,0.0
1,1,2025-02-10,8,13,3,79.9,5.0
2,1,2025-02-10,8,2,4,89.9,10.0
3,2,2025-02-19,15,11,3,199.9,5.0
4,2,2025-02-19,15,18,4,54.9,10.0

In [ ]:
print("Linhas:", len(df_bronze))
print("Colunas:", df_bronze.columns.tolist())

## 6. Salvar a Bronze

Usaremos `to_sql()` para carregar o DataFrame no PostgreSQL.

In [6]:
df_bronze.to_sql(
    "vendas_bronze",
    con=engine,
    schema="etl",
    if_exists="replace",
    index=False
)

print("Bronze carregada!")

Bronze carregada!

## 7. Consultar a Bronze com SQL

In [7]:
sql = text(
    '''
    SELECT *
    FROM etl.vendas_bronze
    LIMIT 10;
    '''
)

with engine.connect() as conn:
    df_teste_bronze = pd.read_sql(sql, conn)

df_teste_bronze

,id_pedido,data_pedido,id_cliente,id_produto,quantidade,preco_unitario,desconto
0,1,2025-02-10,8,6,2,159.9,0.0
1,1,2025-02-10,8,13,3,79.9,5.0
2,1,2025-02-10,8,2,4,89.9,10.0
3,2,2025-02-19,15,11,3,199.9,5.0
4,2,2025-02-19,15,18,4,54.9,10.0
5,2,2025-02-19,15,7,1,189.9,0.0
6,2,2025-02-19,15,14,2,169.9,0.0
7,3,2025-02-28,2,16,4,69.9,10.0
8,3,2025-02-28,2,5,1,139.9,0.0
9,4,2025-03-09,9,3,1,69.9,0.0

# 🥈 SILVER

A Silver contém dados **limpos e tratados**.

Vamos usar Pandas para:

1. remover valores ausentes;
2. calcular valor bruto;
3. calcular desconto;
4. calcular valor líquido.

In [8]:
df_silver = df_bronze.copy()

df_silver.head()

,id_pedido,data_pedido,id_cliente,id_produto,quantidade,preco_unitario,desconto
0,1,2025-02-10,8,6,2,159.9,0.0
1,1,2025-02-10,8,13,3,79.9,5.0
2,1,2025-02-10,8,2,4,89.9,10.0
3,2,2025-02-19,15,11,3,199.9,5.0
4,2,2025-02-19,15,18,4,54.9,10.0

## 8. Limpeza dos dados

In [9]:
print("Antes:", len(df_silver))

df_silver = df_silver.dropna()

print("Depois:", len(df_silver))

Antes: 180
Depois: 180

## 9. Valor bruto

```text
valor_bruto = quantidade × preco_unitario
```

In [10]:
df_silver["valor_bruto"] = (
    df_silver["quantidade"] *
    df_silver["preco_unitario"]
)

df_silver[
    ["quantidade", "preco_unitario", "valor_bruto"]
].head()

   quantidade  preco_unitario  valor_bruto
0           2           159.9        319.8
1           3            79.9        239.7
2           4            89.9        359.6
3           3           199.9        599.7
4           4            54.9        219.6

## 10. Valor do desconto

```text
valor_desconto = valor_bruto × desconto / 100
```

In [11]:
df_silver["valor_desconto"] = (
    df_silver["valor_bruto"] *
    df_silver["desconto"] / 100
)

df_silver[
    ["valor_bruto", "desconto", "valor_desconto"]
].head()

   valor_bruto  desconto  valor_desconto
0        319.8       0.0           0.000
1        239.7       5.0          11.985
2        359.6      10.0          35.960
3        599.7       5.0          29.985
4        219.6      10.0          21.960

## 11. Valor líquido

```text
valor_liquido = valor_bruto - valor_desconto
```

In [12]:
df_silver["valor_liquido"] = (
    df_silver["valor_bruto"] -
    df_silver["valor_desconto"]
)

df_silver[
    ["valor_bruto", "valor_desconto", "valor_liquido"]
].head()

   valor_bruto  valor_desconto  valor_liquido
0        319.8           0.000        319.800
1        239.7          11.985        227.715
2        359.6          35.960        323.640
3        599.7          29.985        569.715
4        219.6          21.960        197.640

## 12. Visualizar a Silver

In [13]:
df_silver.head(10)

,id_pedido,data_pedido,id_cliente,id_produto,quantidade,preco_unitario,desconto,valor_bruto,valor_desconto,valor_liquido
0,1,2025-02-10,8,6,2,159.9,0.0,319.8,0.000,319.800
1,1,2025-02-10,8,13,3,79.9,5.0,239.7,11.985,227.715
2,1,2025-02-10,8,2,4,89.9,10.0,359.6,35.960,323.640
3,2,2025-02-19,15,11,3,199.9,5.0,599.7,29.985,569.715
4,2,2025-02-19,15,18,4,54.9,10.0,219.6,21.960,197.640
5,2,2025-02-19,15,7,1,189.9,0.0,189.9,0.000,189.900
6,2,2025-02-19,15,14,2,169.9,0.0,339.8,0.000,339.800
7,3,2025-02-28,2,16,4,69.9,10.0,279.6,27.960,251.640
8,3,2025-02-28,2,5,1,139.9,0.0,139.9,0.000,139.900
9,4,2025-03-09,9,3,1,69.9,0.0,69.9,0.000,69.900

## 13. Carregar a Silver no PostgreSQL

Destino:

```text
etl.vendas_silver
```

In [14]:
df_silver.to_sql(
    "vendas_silver",
    con=engine,
    schema="etl",
    if_exists="replace",
    index=False
)

print("Silver carregada!")

Silver carregada!

# 🥇 GOLD

A Gold contém dados **prontos para consumo**.

Neste exemplo:

> Faturamento total e quantidade vendida por produto.

## 14. SQL explícito para criar a Gold

```sql
SELECT
    id_produto,
    SUM(quantidade) AS quantidade_vendida,
    SUM(valor_liquido) AS faturamento
FROM etl.vendas_silver
GROUP BY id_produto
ORDER BY faturamento DESC;
```

In [15]:
sql_gold = text(
    '''
    SELECT
        id_produto,
        SUM(quantidade) AS quantidade_vendida,
        SUM(valor_liquido) AS faturamento
    FROM etl.vendas_silver
    GROUP BY id_produto
    ORDER BY faturamento DESC;
    '''
)

## 15. Executar a consulta Gold e carregar no Pandas

In [16]:
with engine.connect() as conn:
    df_gold = pd.read_sql(sql_gold, conn)

df_gold.head(10)

   id_produto  quantidade_vendida  faturamento
0          10                30.0     6997.200
1          14                36.0     5776.600
2           8                42.0     5040.120
3          11                26.0     5017.490
4           4                32.0     4437.040
5          12                16.0     4254.480
6           5                27.0     3630.405
7           2                42.0     3524.080
8           7                18.0     3304.260
9           6                22.0     3261.960

## 16. Carregar a Gold no PostgreSQL

In [17]:
df_gold.to_sql(
    "vendas_gold",
    con=engine,
    schema="etl",
    if_exists="replace",
    index=False
)

print("Gold carregada!")

Gold carregada!

## 17. Consultar a Gold

In [18]:
sql = text(
    '''
    SELECT *
    FROM etl.vendas_gold
    ORDER BY faturamento DESC
    LIMIT 10;
    '''
)

with engine.connect() as conn:
    resultado = pd.read_sql(sql, conn)

resultado

   id_produto  quantidade_vendida  faturamento
0          10                30.0     6997.200
1          14                36.0     5776.600
2           8                42.0     5040.120
3          11                26.0     5017.490
4           4                32.0     4437.040
5          12                16.0     4254.480
6           5                27.0     3630.405
7           2                42.0     3524.080
8           7                18.0     3304.260
9           6                22.0     3261.960

# 18. Validando as três camadas

Podemos verificar a quantidade de registros em cada camada.

In [19]:
sql = text(
    '''
    SELECT
        (SELECT COUNT(*) FROM etl.vendas_bronze) AS bronze,
        (SELECT COUNT(*) FROM etl.vendas_silver) AS silver,
        (SELECT COUNT(*) FROM etl.vendas_gold) AS gold;
    '''
)

with engine.connect() as conn:
    df_contagem = pd.read_sql(sql, conn)

df_contagem

   bronze  silver  gold
0     180     180    18

# 19. Outra Gold — faturamento por cliente

Uma mesma Silver pode alimentar várias tabelas Gold.

In [ ]:
sql_gold_cliente = text(
    '''
    SELECT
        id_cliente,
        COUNT(DISTINCT id_pedido) AS quantidade_pedidos,
        SUM(valor_liquido) AS faturamento
    FROM etl.vendas_silver
    GROUP BY id_cliente
    ORDER BY faturamento DESC;
    '''
)

with engine.connect() as conn:
    df_gold_cliente = pd.read_sql(sql_gold_cliente, conn)

df_gold_cliente.head(10)

In [ ]:
df_gold_cliente.to_sql(
    "faturamento_cliente_gold",
    con=engine,
    schema="etl",
    if_exists="replace",
    index=False
)

print("Gold de clientes carregada!")

# 20. Fluxo completo

```text
                  POSTGRESQL
                       │
                       │ SELECT
                       ▼
              ┌─────────────────┐
              │     BRONZE      │
              │ vendas_bronze   │
              └────────┬────────┘
                       │
                       │ Pandas
                       │ limpeza
                       │ cálculos
                       ▼
              ┌─────────────────┐
              │     SILVER      │
              │ vendas_silver   │
              └────────┬────────┘
                       │
                       │ SQL
                       │ GROUP BY / SUM
                       ▼
              ┌─────────────────┐
              │      GOLD       │
              │   vendas_gold   │
              └────────┬────────┘
                       │
                       ▼
                  Power BI
```

| Tecnologia | Uso |
|---|---|
| PostgreSQL | Banco de dados |
| SQLAlchemy Core | Conexão e SQL |
| `text()` | SQL explícito |
| Pandas | DataFrames e transformações |
| `read_sql()` | PostgreSQL → Pandas |
| `to_sql()` | Pandas → PostgreSQL |

# 📝 Exercícios

### Exercício 1 — Bronze
Altere a consulta Bronze para trazer também o `status` do pedido.

### Exercício 2 — Silver
Crie uma coluna `ticket_medio_item`:

```text
valor_liquido / quantidade
```

### Exercício 3 — Silver
Mantenha somente registros com `quantidade > 1`.

### Exercício 4 — Gold
Crie uma Gold com:

```text
id_cliente
faturamento
```

### Exercício 5 — Gold
Crie uma Gold com:

```text
id_produto
quantidade_vendida
faturamento
```

e mantenha somente produtos com faturamento maior que 1.000.

### Desafio final 🚀
Crie uma Gold de **faturamento mensal**:

```text
mes
faturamento
```

Dica:

```sql
DATE_TRUNC('month', data_pedido)
```